#################### Deployment ####################
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rappels-deployment
  labels:
    app: rappels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rappels
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rappels
    spec:
      containers:
      - name: rappels-container
        image: registry.gitlab.com/gitlabodix/cvtheque-rappels-ms-prod
        args: ["--spring.profiles.active=prod"]
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
#################### Service ####################
---
apiVersion: v1
kind: Service
metadata:
  name: rappels-ms
spec:
  selector:
    app: rappels
  ports:
    - port: 8003
      targetPort: 8003


